server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tack_together?useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: dn123456
    username: bookmaster
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        hbm2ddl:
          auto: create-drop
    open-in-view: false
    show-sql: false